### ISSUE TITLE
Docker work also available at our code instance

### ISSUE THREAD

**Issue by marcinkuzminski** [ckulka/rhodecode-ce#1]
Thanks for the work. We have also one other contributor that creates docker container. Maybe you can use some knowledge from it. 

Please check: https://code.rhodecode.com/rhodecode-enterprise-ce-docker

**Comment by ckulka** [comment]
Hi @marcinkuzminski , thanks for the link, I checked his work out back when I initially checked what's already out there. 

This is just a quick dabble for now, checking if I can - following the Docker spirit - properly separate the three components into separate containers (VCS Server, Rhodecode and the database) as opposed to installing and running it in parallel in a single container like the existing repo does.

If I'm in any way successful, I'll add repositories to https://code.rhodecode.com and see how things go.

**Comment by ckulka** [comment]
Hi @marcinkuzminski , now that it's at a reasonably stable, I forked all three repos to <https://code.rhodecode.com>

**Comment by marcinkuzminski** [comment]
Thanks @ckulka, that's awesome ! We'll try to advertise this somewhere.
